language: python
cache: pip
python:
  - 2.7
  - 3.6
install:
  - pip install flake8
before_script:
  # stop the build if there are Python syntax errors, PEP8 violations, undefined names
  - flake8 . --count --select=E,F821,F822,F823 --max-line-length=127 --show-source --statistics
  # exit-zero treats all errors as warnings.  GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
  - true  # add other tests here

matrix:
  include:
    - language: node_js
      python:
      node_js:
        - 8
      install:
      ## linters for json and JavaScript files
        - npm i -g eslint --save-dev
        - npm install eslint-plugin-json --save-dev -g
        - npm install -g jshint
      ## Data model validator
        - npm install -g fiware-model-validator
      before_script:
        - eslint --ext .json .
        - jshint .
        - validate -p .
      script:
        - true

notifications:
  on_success: change
  on_failure: always
